version: '3.8'
services:
    oai_ausf:
        container_name: oai-ausf
        image: oai-ausf:latest
        environment:
            - TZ=Europe/Paris
            - INSTANCE_ID=0
            - PID_DIR=/var/run
            - AUSF_NAME=OAI_AUSF
            - SBI_IF_NAME=eth0
            - SBI_PORT=80
            - USE_FQDN_DNS=yes
            - UDM_IP_ADDRESS=192.168.70.134
            - UDM_PORT=80
            - UDM_VERSION_NB=v1
            - UDM_FQDN=oai_udm
        network_mode: host
        volumes:
            - ./ausf-healthcheck.sh:/openair-ausf/bin/ausf-healthcheck.sh
        healthcheck:
            test: /bin/bash -c "/openair-ausf/bin/ausf-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 5