version: '3.8'
services:
    oai-nssf:
        container_name: "oai-nssf"
        image: oai-nssf:latest
        environment:
            - INSTANCE=0
            - TZ=Europe/Paris
            - PID_DIRECTORY=/var/run
            - NSSF_NAME=oai-nssf
            - NSSF_FQDN=nssf.oai-5gcn.eur
            - SBI_IF_NAME=eth0
            - SBI_PORT=80
            - SBI_API_VERSION=v1
            - SBI_PORT_HTTP1=80
            - SBI_PORT_HTTP2=8080
            - NSSF_SLICE_CONFIG=/openair-nssf/etc/nssf_slice_config.json
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        volumes: 
            - ./nssf_slice_config.json:/openair-nssf/etc/nssf_slice_config.json
        healthcheck:
            test: /bin/bash -c "pgrep oai_nssf"
            interval: 10s
            timeout: 5s
            retries: 5
        network_mode: host