version: '3.8'
services:
     oai-gnb:
        image: oai-gnb:develop
        privileged: true
        container_name: rfsim5g-oai-gnb
        environment: 
            RFSIMULATOR: server
            USE_SA_TDD_MONO: 'yes'
            GNB_NAME: gnb-rfsim
            TAC: 40960
            MCC: '208'
            MNC: '95'
            MNC_LENGTH: 2
            NSSAI_SST: 222
            NSSAI_SD0: 123
            NSSAI_SD1: 112233
            AMF_IP_ADDRESS: 192.168.70.132
            GNB_NGA_IF_NAME: eth0
            GNB_NGA_IP_ADDRESS: 192.168.70.141
            GNB_NGU_IF_NAME: eth0
            GNB_NGU_IP_ADDRESS: 192.168.70.141
            USE_ADDITIONAL_OPTIONS: --sa -E --rfsim
        network_mode: host
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
