version: '3.8'
services:
    oai_smf_slice3:
        container_name: oai-smf-slice3
        image: oai-smf:latest
        environment:
            - TZ=Europe/Paris
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
            - SMF_INTERFACE_NAME_FOR_N4=eth0
            - SMF_INTERFACE_NAME_FOR_SBI=eth0
            - SMF_INTERFACE_PORT_FOR_SBI=80
            - SMF_INTERFACE_HTTP2_PORT_FOR_SBI=8080
            - SMF_API_VERSION=v1
            - DEFAULT_DNS_IPV4_ADDRESS=192.168.18.129
            - DEFAULT_DNS_SEC_IPV4_ADDRESS=192.168.18.129
            - AMF_IPV4_ADDRESS=192.168.70.138
            - AMF_PORT=80
            - AMF_API_VERSION=v1
            - AMF_FQDN=oai_amf
            - UDM_IPV4_ADDRESS=192.168.70.134
            - UDM_PORT=80
            - UDM_API_VERSION=v1
            - UDM_FQDN=localhost
            - UPF_IPV4_ADDRESS=0.0.0.0
            - UPF_FQDN_0=localhost
            - NRF_IPV4_ADDRESS=192.168.70.137
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - NRF_FQDN=oai_nrf_slice3
            - USE_NETWORK_INSTANCE=yes
            - REGISTER_NRF=yes
            - DISCOVER_UPF=yes
            - USE_FQDN_DNS=no
            - NSSAI_SST1=4
            - NSSAI_SD1=4
        extra_hosts:
            - "gw1.vppupf.node.5gcn.mnc95.mcc208.3gppnetwork.org:192.168.70.202"
        volumes:
            - ./smf-healthcheck.sh:/openair-smf/bin/smf-healthcheck.sh
        healthcheck:
             test: /bin/bash -c "/openair-smf/bin/smf-healthcheck.sh"
             interval: 10s
             timeout: 5s
             retries: 5
        network_mode: host