version: '3.8'
services:
    oai_udm:
        container_name: oai-udm
        image: oai-udm:latest
        environment:
            - TZ=Europe/Paris
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
            - UDM_NAME=OAI_UDM
            - SBI_IF_NAME=eth0
            - SBI_PORT=80
            - UDM_VERSION_NB=v1
            - USE_FQDN_DNS=no
            - UDR_IP_ADDRESS=192.168.70.133
            - UDR_PORT=80
            - UDR_VERSION_NB=v1
            - UDR_FQDN=oai_udr
        network_mode: host
        volumes:
            - ./udm-healthcheck.sh:/openair-udm/bin/udm-healthcheck.sh
        healthcheck:
            test: /bin/bash -c "/openair-udm/bin/udm-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 5