version: '3.8'
services:
    oai-ext-dn:
        image: ubuntu:latest
        privileged: true
        container_name: "oai-ext-dn"
        entrypoint: /bin/bash -c \
              "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;"\
              "ip route add 12.1.1.0/24 via 192.168.73.202 dev eth0; sleep infinity"
        command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
        network_mode: host
