version: '3.8'
services:
    ueransim:
        container_name: ueransim
        image: ue:latest
        privileged: true
        environment:
            # UE Config Parameters
            - NUMBER_OF_UE=1
            - IMSI=208950000000031
            - KEY=0C0A34601D4F07677303652C0462535B
            - OP=63bfa50ee6523365ff14c1f45f88737d
            - OP_TYPE=OPC
            - AMF_VALUE=8000
            - IMEI=356938035643803
            - IMEI_SV=0035609204079514
            - GNB_IP_ADDRESS=192.168.60.11
            - PDU_TYPE=IPv4
            - APN=default
            - SST_C=1
            - SD_C=1
            - SST_D=1
            - SD_D=1
        network_mode: host
        healthcheck:
            test: /bin/bash -c "ifconfig uesimtun0"
            interval: 10s
            timeout: 5s
            retries: 5
